inheritFrom: _universal
pipeline:
  - align
  - assemble
  - exportClones
mixins:
  - type: SetSpecies
    species: hs
  - type: LeftAlignmentBoundaryNoPoint
    floating: false
  - type: RightAlignmentBoundaryNoPoint
    floating: true
    geneType: J
align:
  inheritFrom: align_kaligner2_4.0
assemble:
  inheritFrom: assemble_universal
  overrides:
    cloneAssemblerParameters:
      separateByV: true
      separateByJ: true